#include "home/snapshot.hpp"

#include <algorithm>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <utility>

namespace home {
namespace {
Result<WorldSnapshot> parse_error(const char* m){return Result<WorldSnapshot>::failure(ErrorCode::SerializationError,m);}
bool has_zone(const WorldSnapshot&s,ZoneId z){return std::any_of(s.zones.begin(),s.zones.end(),[&](const ZoneRecord&x){return x.id==z;});}
const EntityRecord* find_entity(const WorldSnapshot&s,EntityId e){auto i=std::find_if(s.entities.begin(),s.entities.end(),[&](const EntityRecord&x){return x.id==e;});return i==s.entities.end()?nullptr:&*i;}
const PlayerLifeState* find_life(const WorldSnapshot&s,EntityId e){auto i=std::find_if(s.player_life.begin(),s.player_life.end(),[&](const PlayerLifeState&x){return x.entity==e;});return i==s.player_life.end()?nullptr:&*i;}
bool valid_player(const WorldSnapshot&s,EntityId e){const auto*r=find_entity(s,e);return r&&r->kind==EntityKind::Avatar&&find_life(s,e);}
bool valid_life_shape(const PlayerLifeState&x){return x.entity.valid()&&static_cast<unsigned>(x.stage)<=static_cast<unsigned>(LifeStage::Elder)&&static_cast<unsigned>(x.presence)<=static_cast<unsigned>(LifePresence::Deceased)&&x.updated_world_minute>=x.born_world_minute&&x.sequence!=0;}
Result<void> validate_social(const WorldSnapshot&s,std::uint64_t now){
 std::vector<std::pair<EntityId,EntityId>> keys; std::vector<HouseholdId> hids; std::vector<EntityId> members;
 for(const auto&r:s.relationships){if(!r.from.valid()||!r.to.valid()||r.from==r.to||static_cast<unsigned>(r.kind)>static_cast<unsigned>(RelationshipKind::Dependent)||r.affinity<kRelationshipAffinityMinimum||r.affinity>kRelationshipAffinityMaximum||r.trust<kRelationshipTrustMinimum||r.trust>kRelationshipTrustMaximum||r.sequence==0||r.updated_world_minute>now||!valid_player(s,r.from)||!valid_player(s,r.to))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot relationship state is invalid");auto k=std::pair{r.from,r.to};if(std::find(keys.begin(),keys.end(),k)!=keys.end())return Result<void>::failure(ErrorCode::AlreadyExists,"duplicate snapshot relationship");keys.push_back(k);}
 for(const auto&h:s.households){if(!h.id.valid()||h.name.empty()||h.members.empty()||h.sequence==0||h.updated_world_minute>now||(h.home_zone&&!has_zone(s,*h.home_zone)))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot household state is invalid");if(std::find(hids.begin(),hids.end(),h.id)!=hids.end())return Result<void>::failure(ErrorCode::AlreadyExists,"duplicate snapshot household id");hids.push_back(h.id);auto local=h.members;std::sort(local.begin(),local.end(),[](EntityId a,EntityId b){return a.value()<b.value();});if(std::adjacent_find(local.begin(),local.end())!=local.end())return Result<void>::failure(ErrorCode::AlreadyExists,"duplicate snapshot household member");for(auto m:local){if(!valid_player(s,m))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot household member lacks canonical avatar life state");if(std::find(members.begin(),members.end(),m)!=members.end())return Result<void>::failure(ErrorCode::AlreadyExists,"snapshot player belongs to multiple households");members.push_back(m);}}
 return Result<void>::success();
}
Result<void> validate_items(const WorldSnapshot&s,std::uint64_t now){std::vector<ItemId> ids;for(const auto&i:s.items){if(!i.id.valid()||i.archetype_key.empty()||i.display_name.empty()||static_cast<unsigned>(i.kind)>static_cast<unsigned>(ItemKind::Material)||i.quantity==0||i.max_stack==0||i.quantity>i.max_stack||i.durability>kItemDurabilityMaximum||i.sequence==0||i.updated_world_minute>now||(i.owner&&i.zone))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot item state is invalid");if(i.owner&&!valid_player(s,*i.owner))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot item owner lacks canonical avatar life state");if(i.zone&&!has_zone(s,*i.zone))return Result<void>::failure(ErrorCode::ValidationFailed,"snapshot item references a missing zone");if(std::find(ids.begin(),ids.end(),i.id)!=ids.end())return Result<void>::failure(ErrorCode::AlreadyExists,"duplicate snapshot item id");ids.push_back(i.id);}return Result<void>::success();}
} // namespace

Result<std::string> encode_snapshot(const WorldSnapshot&s){
 if(!s.world.valid())return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot requires a valid world id");
 if(s.clock_config.real_milliseconds_per_home_minute==0||s.clock_remainder>=s.clock_config.real_milliseconds_per_home_minute)return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot clock state is invalid");
 if(!valid_calendar_date(s.calendar_config.epoch))return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot calendar epoch is invalid");
 EventCatalog ev;for(const auto&x:s.events){auto r=ev.add(x);if(!r)return Result<std::string>::failure(r.error().code,r.error().message);}ClimateCatalog cc;for(const auto&x:s.climates){if(!has_zone(s,x.zone)||cc.find(x.zone))return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot climate is invalid");auto r=cc.set(x);if(!r)return Result<std::string>::failure(r.error().code,r.error().message);}WeatherLedger ww;for(const auto&x:s.weather){if(!has_zone(s,x.zone)||!cc.find(x.zone)||ww.find(x.zone))return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot weather is invalid");auto r=ww.set(x);if(!r)return Result<std::string>::failure(r.error().code,r.error().message);}
 auto av=validate_world_affect_state(s.affect);if(!av)return Result<std::string>::failure(av.error().code,av.error().message);auto an=validate_world_anchor_state(s.anchor);if(!an)return Result<std::string>::failure(an.error().code,an.error().message);
 const auto now=s.world_time.milliseconds/60000ULL;std::vector<EntityId> life_ids,dyn_ids;
 for(const auto&x:s.player_life){if(!valid_life_shape(x)||x.born_world_minute>now||x.updated_world_minute>now||!find_entity(s,x.entity)||find_entity(s,x.entity)->kind!=EntityKind::Avatar||(x.home_zone&&!has_zone(s,*x.home_zone))||std::find(life_ids.begin(),life_ids.end(),x.entity)!=life_ids.end())return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot player life state is invalid");life_ids.push_back(x.entity);}
 for(const auto&x:s.player_dynamics){auto v=validate_player_dynamics_shape(x);const auto*l=find_life(s,x.entity);if(!v||x.updated_world_minute>now||!valid_player(s,x.entity)||!l||x.updated_world_minute<l->born_world_minute||(l->presence==LifePresence::Deceased&&x.autonomy.mode!=AutonomyMode::Disabled)||std::find(dyn_ids.begin(),dyn_ids.end(),x.entity)!=dyn_ids.end())return Result<std::string>::failure(ErrorCode::ValidationFailed,"snapshot player dynamics state is invalid");dyn_ids.push_back(x.entity);}
 auto sv=validate_social(s,now);if(!sv)return Result<std::string>::failure(sv.error().code,sv.error().message);auto iv=validate_items(s,now);if(!iv)return Result<std::string>::failure(iv.error().code,iv.error().message);
 std::ostringstream o;o<<"HOME_SNAPSHOT "<<kSnapshotFormatVersion<<'\n';o<<"WORLD "<<s.world.value()<<' '<<s.revision.value()<<'\n';o<<"CLOCK "<<s.clock_config.real_milliseconds_per_home_minute<<' '<<s.world_time.milliseconds<<' '<<s.clock_remainder<<'\n';o<<"CALENDAR "<<s.calendar_config.epoch.year<<' '<<s.calendar_config.epoch.month<<' '<<s.calendar_config.epoch.day<<'\n';
 o<<"EVENTS "<<s.events.size()<<'\n';for(const auto&x:s.events){o<<"V "<<x.id.value()<<' '<<static_cast<unsigned>(x.kind)<<' '<<x.priority<<' '<<x.rule.month<<' '<<x.rule.day<<' '<<x.rule.duration_days<<' '<<x.affinities.size()<<' '<<std::quoted(x.key)<<' '<<std::quoted(x.display_name);for(const auto&a:x.affinities)o<<' '<<std::quoted(a);o<<'\n';}
 o<<"CLIMATES "<<s.climates.size()<<'\n';for(const auto&x:s.climates)o<<"K "<<x.zone.value()<<' '<<x.mean_temperature_millicelsius<<' '<<x.wetness_permille<<' '<<x.wind_permille<<' '<<x.seed<<'\n';
 o<<"WEATHER "<<s.weather.size()<<'\n';for(const auto&x:s.weather)o<<"W "<<x.zone.value()<<' '<<static_cast<unsigned>(x.intensity)<<' '<<static_cast<unsigned>(x.previous_intensity)<<' '<<x.temperature_millicelsius<<' '<<x.cloud_permille<<' '<<x.precipitation_permille<<' '<<x.wind_mm_per_second<<' '<<x.sequence<<' '<<x.age_minutes<<'\n';
 o<<"AFFECT "<<static_cast<unsigned>(s.affect.tone)<<' '<<s.affect.valence_milli<<' '<<s.affect.intensity_permille<<' '<<s.affect.stability_permille<<'\n';o<<"ANCHOR "<<static_cast<unsigned>(s.anchor.anchor)<<' '<<s.anchor.strength_permille<<' '<<static_cast<unsigned>(s.anchor.source)<<' '<<std::quoted(s.anchor.authority)<<'\n';
 o<<"LIFE "<<s.player_life.size()<<'\n';for(const auto&x:s.player_life)o<<"L "<<x.entity.value()<<' '<<static_cast<unsigned>(x.stage)<<' '<<static_cast<unsigned>(x.presence)<<' '<<(x.home_zone?x.home_zone->value():0)<<' '<<x.born_world_minute<<' '<<x.updated_world_minute<<' '<<x.sequence<<'\n';
 o<<"DYNAMICS "<<s.player_dynamics.size()<<'\n';for(const auto&x:s.player_dynamics){o<<"D "<<x.entity.value();for(auto v:x.needs.values)o<<' '<<v;o<<' '<<x.mood.valence<<' '<<x.mood.arousal<<' '<<static_cast<unsigned>(x.mood.band)<<' '<<static_cast<unsigned>(x.autonomy.mode)<<' '<<x.autonomy.initiative_limit_per_hour<<' '<<(x.autonomy.may_change_zone?1:0)<<' '<<(x.autonomy.may_interact_with_entities?1:0)<<' '<<x.updated_world_minute<<' '<<x.sequence<<' '<<std::quoted(x.active_drive)<<'\n';}
 o<<"RELATIONSHIPS "<<s.relationships.size()<<'\n';for(const auto&x:s.relationships)o<<"R "<<x.from.value()<<' '<<x.to.value()<<' '<<static_cast<unsigned>(x.kind)<<' '<<x.affinity<<' '<<x.trust<<' '<<x.updated_world_minute<<' '<<x.sequence<<'\n';
 o<<"HOUSEHOLDS "<<s.households.size()<<'\n';for(const auto&x:s.households){o<<"H "<<x.id.value()<<' '<<(x.home_zone?x.home_zone->value():0)<<' '<<x.updated_world_minute<<' '<<x.sequence<<' '<<x.members.size()<<' '<<std::quoted(x.name);for(auto m:x.members)o<<' '<<m.value();o<<'\n';}
 o<<"ITEMS "<<s.items.size()<<'\n';for(const auto&x:s.items)o<<"I "<<x.id.value()<<' '<<static_cast<unsigned>(x.kind)<<' '<<x.quantity<<' '<<x.max_stack<<' '<<x.durability<<' '<<(x.owner?x.owner->value():0)<<' '<<(x.zone?x.zone->value():0)<<' '<<x.updated_world_minute<<' '<<x.sequence<<' '<<std::quoted(x.archetype_key)<<' '<<std::quoted(x.display_name)<<'\n';
 o<<"ENTITIES "<<s.entities.size()<<'\n';for(const auto&x:s.entities)o<<"E "<<x.id.value()<<' '<<static_cast<unsigned>(x.kind)<<' '<<(x.persistent?1:0)<<' '<<std::quoted(x.archetype)<<' '<<std::quoted(x.display_name)<<' '<<x.transform.position.x<<' '<<x.transform.position.y<<' '<<x.transform.position.z<<' '<<x.transform.rotation.pitch<<' '<<x.transform.rotation.yaw<<' '<<x.transform.rotation.roll<<'\n';
 o<<"ZONES "<<s.zones.size()<<'\n';for(const auto&x:s.zones)o<<"Z "<<x.id.value()<<' '<<static_cast<unsigned>(x.kind)<<' '<<(x.persistent?1:0)<<' '<<(x.parent?x.parent->value():0)<<' '<<std::quoted(x.key)<<' '<<std::quoted(x.display_name)<<'\n';o<<"CONNECTIONS "<<s.connections.size()<<'\n';for(const auto&x:s.connections)o<<"C "<<x.from.value()<<' '<<x.to.value()<<' '<<(x.bidirectional?1:0)<<' '<<(x.traversable?1:0)<<' '<<std::quoted(x.tag)<<'\n';o<<"PLACEMENTS "<<s.placements.size()<<'\n';for(const auto&x:s.placements)o<<"P "<<x.entity.value()<<' '<<x.zone.value()<<'\n';o<<"END\n";return Result<std::string>::success(o.str());
}

Result<WorldSnapshot> decode_snapshot(std::string_view encoded){
 std::istringstream in{std::string(encoded)};std::string m;unsigned f=0;if(!(in>>m>>f)||m!="HOME_SNAPSHOT"||f<1||f>kSnapshotFormatVersion)return parse_error("unsupported or malformed snapshot header");WorldSnapshot s{};std::uint64_t w=0,r=0;if(!(in>>m>>w>>r)||m!="WORLD"||w==0)return parse_error("malformed snapshot world header");s.world=WorldId{w};s.revision=WorldRevision{r};
 if(f>=2){std::uint64_t ratio=0,t=0,rem=0;if(!(in>>m>>ratio>>t>>rem)||m!="CLOCK"||ratio==0||rem>=ratio)return parse_error("malformed snapshot clock state");s.clock_config.real_milliseconds_per_home_minute=ratio;s.world_time=WorldTime{t};s.clock_remainder=rem;}
 if(f>=3){int y=0;unsigned mo=0,d=0;if(!(in>>m>>y>>mo>>d)||m!="CALENDAR")return parse_error("malformed snapshot calendar state");s.calendar_config.epoch=CalendarDate{y,mo,d};if(!valid_calendar_date(s.calendar_config.epoch))return parse_error("invalid snapshot calendar epoch");}
 std::size_t n=0;
 if(f>=4){if(!(in>>m>>n)||m!="EVENTS")return parse_error("malformed event section");EventCatalog ev;for(std::size_t j=0;j<n;++j){EventDefinition x{};std::uint64_t id=0;unsigned k=0,mo=0,d=0,dur=0;int p=0;std::size_t ac=0;if(!(in>>m>>id>>k>>p>>mo>>d>>dur>>ac>>std::quoted(x.key)>>std::quoted(x.display_name))||m!="V"||id==0||k>static_cast<unsigned>(EventKind::Story))return parse_error("malformed event record");x.id=EventId{id};x.kind=static_cast<EventKind>(k);x.priority=p;x.rule=AnnualDateRule{mo,d,dur};for(std::size_t a=0;a<ac;++a){std::string q;if(!(in>>std::quoted(q)))return parse_error("malformed event affinity");x.affinities.push_back(std::move(q));}if(!ev.add(x))return parse_error("invalid or duplicate event record");s.events.push_back(std::move(x));}}
 if(f>=5){if(!(in>>m>>n)||m!="CLIMATES")return parse_error("malformed climate section");ClimateCatalog cc;for(std::size_t j=0;j<n;++j){std::uint64_t z=0,seed=0;int temp=0;unsigned wet=0,wind=0;if(!(in>>m>>z>>temp>>wet>>wind>>seed)||m!="K"||z==0)return parse_error("malformed climate record");ClimateProfile x{ZoneId{z},temp,wet,wind,seed};if(cc.find(x.zone)||!cc.set(x))return parse_error("invalid or duplicate climate record");s.climates.push_back(x);}if(!(in>>m>>n)||m!="WEATHER")return parse_error("malformed weather section");WeatherLedger wl;for(std::size_t j=0;j<n;++j){std::uint64_t z=0,seq=0;unsigned a=0,b=0,c=0,p=0,wind=0,age=0;int temp=0;if(!(in>>m>>z>>a>>b>>temp>>c>>p>>wind>>seq>>age)||m!="W"||z==0||a>static_cast<unsigned>(RainIntensity::Deluge)||b>static_cast<unsigned>(RainIntensity::Deluge))return parse_error("malformed weather record");WeatherState x{ZoneId{z},static_cast<RainIntensity>(a),static_cast<RainIntensity>(b),temp,c,p,wind,seq,age};if(wl.find(x.zone)||!wl.set(x))return parse_error("invalid or duplicate weather record");s.weather.push_back(x);}}
 if(f>=6){unsigned t=0,ii=0,st=0;int v=0;if(!(in>>m>>t>>v>>ii>>st)||m!="AFFECT"||t>static_cast<unsigned>(WorldTone::Dreamlike))return parse_error("malformed world affect state");s.affect=WorldAffectState{static_cast<WorldTone>(t),v,ii,st};if(!validate_world_affect_state(s.affect))return parse_error("invalid world affect state");unsigned a=0,str=0,src=0;std::string auth;if(!(in>>m>>a>>str>>src>>std::quoted(auth))||m!="ANCHOR"||a>static_cast<unsigned>(ThemeAnchor::HauntedHalloweenRain)||src>static_cast<unsigned>(AnchorSource::AuthorizedOverride))return parse_error("malformed world anchor state");s.anchor=WorldAnchorState{static_cast<ThemeAnchor>(a),str,static_cast<AnchorSource>(src),std::move(auth)};if(!validate_world_anchor_state(s.anchor))return parse_error("invalid world anchor state");}
 if(f>=7){if(!(in>>m>>n)||m!="LIFE")return parse_error("malformed player life section");for(std::size_t j=0;j<n;++j){std::uint64_t e=0,h=0,b=0,u=0,q=0;unsigned st=0,p=0;if(!(in>>m>>e>>st>>p>>h>>b>>u>>q)||m!="L"||e==0||st>static_cast<unsigned>(LifeStage::Elder)||p>static_cast<unsigned>(LifePresence::Deceased)||q==0||u<b)return parse_error("malformed player life record");PlayerLifeState x{};x.entity=EntityId{e};x.stage=static_cast<LifeStage>(st);x.presence=static_cast<LifePresence>(p);if(h)x.home_zone=ZoneId{h};x.born_world_minute=b;x.updated_world_minute=u;x.sequence=q;if(find_life(s,x.entity))return parse_error("duplicate player life entity");s.player_life.push_back(x);}}
 if(f>=8){if(!(in>>m>>n)||m!="DYNAMICS")return parse_error("malformed player dynamics section");for(std::size_t j=0;j<n;++j){PlayerDynamicsState x{};std::uint64_t e=0,u=0,q=0;unsigned band=0,mode=0,init=0;int z=0,it=0;if(!(in>>m>>e)||m!="D"||e==0)return parse_error("malformed player dynamics record");for(auto&v:x.needs.values)if(!(in>>v))return parse_error("malformed player dynamics needs");if(!(in>>x.mood.valence>>x.mood.arousal>>band>>mode>>init>>z>>it>>u>>q>>std::quoted(x.active_drive))||band>static_cast<unsigned>(MoodBand::Elevated)||mode>static_cast<unsigned>(AutonomyMode::Bounded)||(z!=0&&z!=1)||(it!=0&&it!=1))return parse_error("malformed player dynamics record");x.entity=EntityId{e};x.mood.band=static_cast<MoodBand>(band);x.autonomy.mode=static_cast<AutonomyMode>(mode);x.autonomy.initiative_limit_per_hour=init;x.autonomy.may_change_zone=z!=0;x.autonomy.may_interact_with_entities=it!=0;x.updated_world_minute=u;x.sequence=q;if(!validate_player_dynamics_shape(x)||std::any_of(s.player_dynamics.begin(),s.player_dynamics.end(),[&](const PlayerDynamicsState&y){return y.entity==x.entity;}))return parse_error("invalid player dynamics record");s.player_dynamics.push_back(std::move(x));}}
 if(f>=9){if(!(in>>m>>n)||m!="RELATIONSHIPS")return parse_error("malformed relationships section");for(std::size_t j=0;j<n;++j){std::uint64_t a=0,b=0,u=0,q=0;unsigned k=0;std::int32_t af=0,tr=0;if(!(in>>m>>a>>b>>k>>af>>tr>>u>>q)||m!="R"||a==0||b==0||a==b||k>static_cast<unsigned>(RelationshipKind::Dependent)||q==0)return parse_error("malformed relationship record");s.relationships.push_back(RelationshipState{EntityId{a},EntityId{b},static_cast<RelationshipKind>(k),af,tr,u,q});}if(!(in>>m>>n)||m!="HOUSEHOLDS")return parse_error("malformed households section");for(std::size_t j=0;j<n;++j){HouseholdState x{};std::uint64_t id=0,z=0,u=0,q=0;std::size_t mc=0;if(!(in>>m>>id>>z>>u>>q>>mc>>std::quoted(x.name))||m!="H"||id==0||q==0||mc==0)return parse_error("malformed household record");x.id=HouseholdId{id};if(z)x.home_zone=ZoneId{z};x.updated_world_minute=u;x.sequence=q;for(std::size_t a=0;a<mc;++a){std::uint64_t e=0;if(!(in>>e)||e==0)return parse_error("malformed household member");x.members.push_back(EntityId{e});}s.households.push_back(std::move(x));}}
 if(f>=10){if(!(in>>m>>n)||m!="ITEMS")return parse_error("malformed items section");for(std::size_t j=0;j<n;++j){ItemState x{};std::uint64_t id=0,owner=0,zone=0,u=0,q=0;unsigned k=0,qty=0,max=0,dur=0;if(!(in>>m>>id>>k>>qty>>max>>dur>>owner>>zone>>u>>q>>std::quoted(x.archetype_key)>>std::quoted(x.display_name))||m!="I"||id==0||k>static_cast<unsigned>(ItemKind::Material)||qty==0||max==0||qty>max||dur>kItemDurabilityMaximum||q==0||(owner&&zone))return parse_error("malformed item record");x.id=ItemId{id};x.kind=static_cast<ItemKind>(k);x.quantity=qty;x.max_stack=max;x.durability=dur;if(owner)x.owner=EntityId{owner};if(zone)x.zone=ZoneId{zone};x.updated_world_minute=u;x.sequence=q;s.items.push_back(std::move(x));}}
 if(!(in>>m>>n)||m!="ENTITIES")return parse_error("malformed entity section");for(std::size_t j=0;j<n;++j){EntityRecord x{};std::uint64_t id=0;unsigned k=0;int p=0;if(!(in>>m>>id>>k>>p>>std::quoted(x.archetype)>>std::quoted(x.display_name)>>x.transform.position.x>>x.transform.position.y>>x.transform.position.z>>x.transform.rotation.pitch>>x.transform.rotation.yaw>>x.transform.rotation.roll)||m!="E"||id==0||k>static_cast<unsigned>(EntityKind::Environment))return parse_error("malformed entity record");x.id=EntityId{id};x.world=s.world;x.kind=static_cast<EntityKind>(k);x.persistent=p!=0;s.entities.push_back(std::move(x));}
 if(!(in>>m>>n)||m!="ZONES")return parse_error("malformed zone section");for(std::size_t j=0;j<n;++j){ZoneRecord x{};std::uint64_t id=0,parent=0;unsigned k=0;int p=0;if(!(in>>m>>id>>k>>p>>parent>>std::quoted(x.key)>>std::quoted(x.display_name))||m!="Z"||id==0||k>static_cast<unsigned>(ZoneKind::Restricted))return parse_error("malformed zone record");x.id=ZoneId{id};x.world=s.world;x.kind=static_cast<ZoneKind>(k);x.persistent=p!=0;if(parent)x.parent=ZoneId{parent};s.zones.push_back(std::move(x));}
 if(!(in>>m>>n)||m!="CONNECTIONS")return parse_error("malformed connection section");for(std::size_t j=0;j<n;++j){std::uint64_t a=0,b=0;int bi=0,tr=0;std::string tag;if(!(in>>m>>a>>b>>bi>>tr>>std::quoted(tag))||m!="C"||a==0||b==0)return parse_error("malformed connection record");s.connections.push_back(ZoneConnection{ZoneId{a},ZoneId{b},bi!=0,tr!=0,std::move(tag)});}
 if(!(in>>m>>n)||m!="PLACEMENTS")return parse_error("malformed placement section");for(std::size_t j=0;j<n;++j){std::uint64_t e=0,z=0;if(!(in>>m>>e>>z)||m!="P"||e==0||z==0)return parse_error("malformed placement record");s.placements.push_back(SnapshotPlacement{EntityId{e},ZoneId{z}});}if(!(in>>m)||m!="END")return parse_error("snapshot missing END marker");
 const auto now=s.world_time.milliseconds/60000ULL;if(f>=5){ClimateCatalog cc;for(const auto&x:s.climates)if(!has_zone(s,x.zone)||cc.find(x.zone)||!cc.set(x))return parse_error("snapshot climate references missing zone or is invalid");for(const auto&x:s.weather)if(!has_zone(s,x.zone)||!cc.find(x.zone))return parse_error("snapshot weather references missing zone or climate");}if(f>=7)for(const auto&x:s.player_life){const auto*e=find_entity(s,x.entity);if(!e||e->kind!=EntityKind::Avatar||(x.home_zone&&!has_zone(s,*x.home_zone))||x.born_world_minute>now||x.updated_world_minute>now)return parse_error("snapshot player life state is invalid");}if(f>=8)for(const auto&x:s.player_dynamics){const auto*l=find_life(s,x.entity);if(!valid_player(s,x.entity)||!l||x.updated_world_minute>now||x.updated_world_minute<l->born_world_minute||(l->presence==LifePresence::Deceased&&x.autonomy.mode!=AutonomyMode::Disabled))return parse_error("snapshot player dynamics state is invalid");}if(f>=9){auto v=validate_social(s,now);if(!v)return parse_error("snapshot social state is invalid");}if(f>=10){auto v=validate_items(s,now);if(!v)return parse_error("snapshot item state is invalid");}
 return Result<WorldSnapshot>::success(std::move(s));
}

Result<void> save_snapshot_file(const WorldSnapshot&s,const std::string&p){if(p.empty())return Result<void>::failure(ErrorCode::InvalidArgument,"snapshot path must not be empty");auto e=encode_snapshot(s);if(!e)return Result<void>::failure(e.error().code,e.error().message);std::ofstream o(p,std::ios::binary|std::ios::trunc);if(!o)return Result<void>::failure(ErrorCode::SerializationError,"could not open snapshot file for writing");o.write(e.value().data(),static_cast<std::streamsize>(e.value().size()));if(!o)return Result<void>::failure(ErrorCode::SerializationError,"snapshot write failed");return Result<void>::success();}
Result<WorldSnapshot> load_snapshot_file(const std::string&p){if(p.empty())return Result<WorldSnapshot>::failure(ErrorCode::InvalidArgument,"snapshot path must not be empty");std::ifstream i(p,std::ios::binary);if(!i)return Result<WorldSnapshot>::failure(ErrorCode::SerializationError,"could not open snapshot file for reading");std::ostringstream b;b<<i.rdbuf();if(!i.good()&&!i.eof())return Result<WorldSnapshot>::failure(ErrorCode::SerializationError,"snapshot read failed");return decode_snapshot(b.str());}

} // namespace home
